version: '3'
services:
  mysql:
    container_name: mysql
    image: mysql:5.7
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: prestashop
    ports:
      - 3306:3306
    networks:
      - prestashop_network
    volumes:
      - dbdata:/var/lib/mysql

  prestashop:
    container_name: prestashop
    build:
      dockerfile: ./local.Dockerfile
    restart: unless-stopped
    depends_on:
      - mysql
    ports:
      - 8080:80
    environment:
      DB_SERVER: mysql
      DB_NAME: prestashop
      DB_USER: root
      DB_PASSWD: admin
      PS_INSTALL_AUTO: 1
      PS_DOMAIN: localhost:8080
      PS_DEV_MODE: 1
      PS_FOLDER_INSTALL: install-dev
      PS_FOLDER_ADMIN: admin-dev
      ADMIN_MAIL: test@tiltup.io
      ADMIN_PASSWD: Qwerty123!
    networks:
      - prestashop_network
    volumes:
      - psdata:/var/www/html
      - ./docker/php/conf.d/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini
      - type: bind
        source: ./tiltupcryptopaymentsmodule
        target: /var/www/html/modules/tiltupcryptopaymentsmodule
      - type: bind
        source: ./scripts
        target: /tmp/post-install-scripts

networks:
  prestashop_network:

volumes:
  dbdata:
  psdata: