# FOR DEV PURPOSES ONLY!

configuration:
  update:
    TILTUP_MERCHANT_ID: "${MERCHANT_ID}"
    TILTUP_SHOP_ID: "${SHOP_ID}"
    TILTUP_ENV: "${SUBDOMAIN}"
    TILTUP_ENCRYPTION_KEY: "mysecret"
    TILTUP_REDIRECT_IMMEDIATE: "true"

sql:
  - "extra_config.sql"
