# FOR DEV PURPOSES ONLY!

configuration:
  update:
    TILTUP_MERCHANT_ID: "${MERCHANT_ID}"
    TILTUP_SHOP_ID: "${SHOP_ID}"
    TILTUP_ENV: "${NODE_ENV}"
    TILTUP_ENCRYPTION_KEY: "mysecret"

sql:
  - "extra_config.sql"